services:
  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5032:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: chat-api
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=postgres;Username=postgres;Password=mysecretpassword;
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  db:
  redis-data: