import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Live Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white items-center text-gray-900">
          {children}
      </body>
    </html>
  );
}
